export const times = [
    {id: 1, nome: 'Atlético Mineiro', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Atletico_mineiro_galo.png/120px-Atletico_mineiro_galo.png', cor: '#AFD652'},
    {id: 2, nome: 'Bahia', foto: 'https://upload.wikimedia.org/wikipedia/pt/thumb/9/90/ECBahia.png/130px-ECBahia.png'},
    {id: 3, nome: 'Botafogo FR', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Botafogo_de_Futebol_e_Regatas_logo.svg/120px-Botafogo_de_Futebol_e_Regatas_logo.svg.png'},
    {id: 4, nome: 'Ceará', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Cear%C3%A1_Sporting_Club_logo.svg/120px-Cear%C3%A1_Sporting_Club_logo.svg.png'},
    {id: 5, nome: 'Corinthians', foto: 'https://upload.wikimedia.org/wikipedia/pt/thumb/b/b4/Corinthians_simbolo.png/120px-Corinthians_simbolo.png'},
    {id: 6, nome: 'Cruzeiro', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Cruzeiro_Esporte_Clube_%28logo%29.svg/120px-Cruzeiro_Esporte_Clube_%28logo%29.svg.png'},
    {id: 7, nome: 'Flamengo', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flamengo_braz_logo.svg/120px-Flamengo_braz_logo.svg.png'},
    {id: 8, nome: 'Fluminense', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/FFC_crest.svg/130px-FFC_crest.svg.png'},
    {id: 9, nome: 'Fortaleza', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Fortaleza_EC_2018.png/120px-Fortaleza_EC_2018.png'},
    {id: 10, nome: 'Grêmio', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Gremio_logo.svg/120px-Gremio_logo.svg.png'},
    {id: 11, nome: 'Internacional', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/SC_Internacional_Brazil_Logo.svg/120px-SC_Internacional_Brazil_Logo.svg.png'},
    {id: 12, nome: 'Juventude', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/EC_Juventude.svg/140px-EC_Juventude.svg.png'},
    {id: 13, nome: 'Mirassol', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Mirassol_FC_logo.png/150px-Mirassol_FC_logo.png'},
    {id: 14, nome: 'S.E. Palmeiras', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Palmeiras_logo.svg/120px-Palmeiras_logo.svg.png'},
    {id: 15, nome: 'RB Bragantino', foto: 'https://upload.wikimedia.org/wikipedia/pt/thumb/9/9e/RedBullBragantino.png/140px-RedBullBragantino.png'},
    {id: 16, nome: 'Santos', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Santos_Logo.png/120px-Santos_Logo.png'},
    {id: 17, nome: 'São Paulo', foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Brasao_do_Sao_Paulo_Futebol_Clube.svg/120px-Brasao_do_Sao_Paulo_Futebol_Clube.svg.png'},
    {id: 18, nome: 'Sport', foto: 'https://upload.wikimedia.org/wikipedia/pt/thumb/1/17/Sport_Club_do_Recife.png/120px-Sport_Club_do_Recife.png'},
    {id: 19, nome: 'Vasco', foto: 'https://upload.wikimedia.org/wikipedia/pt/thumb/a/ac/CRVascodaGama.png/120px-CRVascodaGama.png'},
    {id: 20, nome: 'Vitória', foto: 'https://upload.wikimedia.org/wikipedia/pt/3/34/Esporte_Clube_Vit%C3%B3ria_logo.png'}, 
]